overrides: update matplotlib env attr def to match nixpkgs
Mismatched vs. upstream can cause problems if this override is applied
atop the nixpkgs one, resulting in e.g.

> error: The ‘env’ attribute set cannot contain any attributes passed to
> derivation.

See
https://github.com/nixos/nixpkgs/commit/0d5041f8054a3a533ca687f8cb93ab702fdbc8c8